version: "3"

services:
  bus_db:
    container_name: bus_database
    restart: always
    environment:
      POSTGRES_DB: web_server_db
      POSTGRES_USER: otavio
      POSTGRES_PASSWORD: Smile@435BMI
      POSTGRES_DATA: /var/lib/postgresql/data/pgdata
    build:
      context: .
      dockerfile: DockerfileDB
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bus_adminer:
    image: adminer
    container_name: bus_adminer
    restart: always
    ports:
      - 8080:8081
    depends_on:
      - bus_db

  bus_web:
    build: .
    container_name: bus_web_service
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - bus_adminer
      - bus_db
      # - smtp
      # - redis
    # stdin_open: true
    # tty: true
  
  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #    - '6379:6379'

volumes:
  db-data:
    driver: local